apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uotq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-uotq@sha256:fd1895c2be66412958ab12647ca3d9928276ab04c4171d2aaa0a072e857008f0
        name: my-nodejs
        resources: {}
status: {}
